name: Build & deploy .NET APP

on:
  push:
    branches: [ "main" ]


env:
  wowshop_image: '${{ secrets.DOCKER_USERNAME }}/julianbookingservce'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Create Docker Image
        run: dotnet publish ./BookingService/BookingService.csproj /t:PublishContainer -r linux-x64
      #- name: change image tag
      #  run: docker tag wowshop ${{ env.wowshop_image }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
   